Improvements to the playbook.
githubixx/ansible-role-cilium-kubernetes pull request #13
Opened 2022-02-13 10:26 UTC by tiagoblackcode

This changes the following:

[Skip BPFFS installation when LSB is not available](https://github.com/githubixx/ansible-role-cilium-kubernetes/commit/748237bf75422b7cedb547961a1ea7b38f6ec2c7)
CentOS does not come with LSB by default. This skips installation of BPFFS when the `ansible_lsb`
fact is not available.

This might not be 100% correct, but it's better than having support only for Ubuntu.

[Install Cilium repository when rendering the template](https://github.com/githubixx/ansible-role-cilium-kubernetes/commit/4f078da30a49bcde415c0c22e14f75231919fe56)
When attempting to render the helm chart template in a clean helm installation, the playbook fails
because the repository has not yet been installed. This makes sure the repository exists before
attempting to render the template.

Additionally, when there are no repositories installed in helm, the `helm repo list` command exists
with an error. In such cases, the playbook would also fail. Now, errors are ignored when listing the
available repositories and the install command is ran wether the repo command failed or the
repository is not yet available. When the `helm repo list` command throws an error not related to
the absence of repositories, the install command will most likely throw it too, so the play will
fail in such cases.

2022-02-14 21:55 UTC, githubixx requested changes
Thanks for the PR! I've added a few comments inline.

2022-02-14 21:55 UTC, githubixx commented on tasks/template.yml
> +
```suggestion
```

2022-02-14 21:55 UTC, githubixx commented on tasks/repo.yml
> +
```suggestion
```

2022-02-14 21:55 UTC, githubixx commented on tasks/install.yml
> +      ansible_lsb.release is version('20.04', '<')
```suggestion
    - ansible_lsb.release is defined 
    - ansible_lsb.release is version('20.04', '<')
```
If you use lists for `when` then they're `AND` by default anyway.

2022-02-14 21:55 UTC, githubixx commented on tasks/delete.yml
> +    ansible_lsb.release is version('20.04', '<')
```suggestion
  when:
    - ansible_lsb.release is defined
    - ansible_lsb.release is version('20.04', '<')
```
If you use lists for `when` then they're `AND` by default anyway.

2022-02-14 21:55 UTC, githubixx commented on tasks/install.yml
> +- include_tasks: repo.yml
```suggestion
- include_tasks: helm_repository.yml
```
Please rename `repo.yml` to `helm_repository.yml`.

2022-02-15 08:11 UTC, tiagoblackcode commented
All fixed.

2022-02-16 18:33 UTC, githubixx approved these changes

2022-02-16 18:33 UTC, merged